[codestyle]
indent_type = 'space'
indent_width = 4
workspace_dir = '/workdir'
lang = 'python'
template_file='/workdir/template.py'
[etc]
download_without_login=false
parallel_download=false
save_no_session_cache=false